language: python
python:
  - "3.6"
# command to install dependencies
before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade pip
  - sudo apt-get install python3-enchant
  - sudo apt-get install python3-setuptools
  - sudo apt-get update
  - sudo apt install ffmpeg
  - sudo pip3 install -r requirements.txt
  - sudo pip3 uninstall numpy
  - sudo pip3 install numpy
# command to run tests
script:
  - python3 spafe/signal.py
