language: python
python:
  - "3.5"
# command to install dependencies
before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools
  - pip3 install --upgrade setuptools
  - pip3 install matplotlib
# command to run tests
script:
  - python3 spafe/tests/test_fbanks.py
